services:
  # Redis service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bullmq-rust-app
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
    command: ["cargo", "run"]

volumes:
  redis-data:
